baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Hans Yu'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Notes'
pageRef = '/notes'
weight = 20

[[menus.main]]
name = 'Collections'
pageRef = '/collections'
weight = 30

[[menus.main]]
name = 'Projects'
pageRef = '/projects'
weight = 40

[[menus.main]]
name = 'About'
pageRef = '/about'
weight = 50

[[module.imports]]
disable = true
path = 'github.com/adityatelange/hugo-PaperMod'

[[module.imports]]
path = 'github.com/nunocoracao/blowfish/v2'

[[module.imports]]
disable = true
path = 'github.com/theNewDynamic/gohugo-theme-ananke/v2'

[params.author]
name = 'Hans Yu'
image = 'ASE_square.jpg'
headline = 'From fluid mechanics to software and data.'
bio = 'Ein Teil jener Kraft, die stets das Gute will und stets das Böse schafft.'

[params.homepage]
showRecent = true
